export const projectsJson = [
  {
    id: 1,
    date: "2024.10 - 2025.02",
    tags: ["FrontEnd", "Bussiness Site", "Milti Language"],
    wrapperImage: "/projects-image/ismiretiket/1.webp",
    images: [
      "/projects-image/ismiretiket/1.webp",
      "/projects-image/ismiretiket/2.webp",
      "/projects-image/ismiretiket/3.webp",
      "/projects-image/ismiretiket/4.webp",
      "/projects-image/ismiretiket/5.webp",
      "/projects-image/ismiretiket/6.webp",
    ],
    wrapperProject: "Ismir Etiket",
    projectName: "Ismir Etiket (Clothing Business Website)",
    sitelink: "https://ismiretiket.netlify.app/",
    githubLink: "https://github.com/mukhammadboburjuraev/ismir",
    techStacks: ["Vite", "React", "Tailwind CSS", "i18next"],
  },
  {
    id: 2,
    date: "2025.03 - 2025.05",
    tags: ["FrontEnd", "Order App", "Coffee"],
    wrapperImage: "/projects-image/mega-coffee/1.webp",
    images: [
      "/projects-image/mega-coffee/1.webp",
      "/projects-image/mega-coffee/2.webp",
      "/projects-image/mega-coffee/3.webp",
      "/projects-image/mega-coffee/4.webp",
      "/projects-image/mega-coffee/5.webp",
    ],
    wrapperProject: "Mega Coffee Order App",
    projectName: "Mega Coffee Order App",
    sitelink: "https://mega-coffeee.netlify.app/",
    githubLink: "https://github.com/mukhammadboburjuraev/mega-coffee-order-app",
    techStacks: ["Vite", "React", "Tailwind CSS", "Axios"],
  },
  {
    id: 3,
    date: "2025.05 - 2025.06",
    tags: ["MERN", "DB", "Authentication"],
    wrapperImage: "/projects-image/cool-pic/1.webp",
    images: [
      "/projects-image/cool-pic/1.webp",
      "/projects-image/cool-pic/2.webp",
      "/projects-image/cool-pic/3.webp",
      "/projects-image/cool-pic/4.webp",
      "/projects-image/cool-pic/5.webp",
    ],
    wrapperProject: "Cool Pic",
    projectName: "Cool Pic - Photo Sharing App",
    sitelink: "https://cool-pic.onrender.com/",
    githubLink: "https://github.com/mukhammadboburjuraev/cool-pic",
    techStacks: [
      "Node JS",
      "React",
      "Tailwind CSS",
      "Cloudinary",
      "MongoDB",
      "CORS",
    ],
  },

  {
    id: 4,
    date: "2025.07 - 2025.08",
    tags: ["MERN", "DB", "Cinema"],
    wrapperImage: "/projects-image/movie-seats/1.webp",
    images: [
      "/projects-image/movie-seats/1.webp",
      "/projects-image/movie-seats/2.webp",
      "/projects-image/movie-seats/3.webp",
      "/projects-image/movie-seats/4.webp",
      "/projects-image/movie-seats/5.webp",
    ],
    wrapperProject: "Movie Seats",
    projectName: "Movie Seats - Movie Seat Reservation App",
    sitelink: "https://movieseats-2t6o.onrender.com/",
    githubLink: "https://github.com/mukhammadboburjuraev/movie-seats",
    techStacks: [
      "Express JS",
      "Vite",
      "React",
      "React DropZone",
      "Tailwind CSS",
      "MongoDB",
    ],
  },
];
